#!/usr/bin/env python3

# Python File: ./lib/system_variables.py
__version__ = "0.1.0"  # Documentation version

MODULE_DOCSTRING = """
Overview:
    The `system_variables.py` module defines system-wide configuration paths and constants
    used throughout the framework. It provides standardized paths for configurations,
    logs, and project directories to ensure consistency across different components.

Core Features:
    - Standardized paths for runtime configurations, logs, and environment files.
    - Predefined logging categories for structured logging.
    - A dynamically resolved project root path for consistent reference.
    - Aggregation of system parameter files for centralized configuration management.

Usage:
    Import this module wherever system-wide constants are required:
        from lib.system_variables import project_root, system_params_filepath

Expected Behavior:
    - Configuration paths should always resolve correctly, ensuring consistency.
    - `max_logfiles` should ideally be configurable via an environment variable.
    - System parameter files should be aggregated dynamically for flexibility.
"""

FUNCTION_DOCSTRINGS = {}

VARIABLE_DOCSTRINGS = {
    "project_root": "Root directory of the project, used for resolving paths dynamically.",
    "project_logs": "Directory where all log files are stored, structured under logs/<package-name>/<module-name>-<timestamp>.log.",
    "project_packages": "Directory path where all Python packages are stored.",
    "env_filepath": "Path to the .env file containing runtime environment variables.",
    "runtime_params_filename": "Filename for the dynamically generated runtime parameters file.",
    "runtime_params_filepath": "Path to the runtime-params.json file, dynamically generated by merging system-wide and project parameters.",
    "system_params_filename": "Filename for the system-wide configuration parameters file.",
    "system_params_filepath": "Path to the system-params.json file, storing global system-wide configurations.",
    "project_params_filename": "Filename for the project-specific parameters file.",
    "project_params_filepath": "Path to the project-params.json file, customized for user-specific configurations.",
    "default_params_filename": "Filename for the default framework-wide parameters file.",
    "default_params_filepath": "Path to the default-params.json file, containing standardized default settings.",
    "system_params_listing": "List of JSON configuration files used for system parameter aggregation, including project-params.json and default-params.json.",
    "max_logfiles": "Maximum number of log files allowed per module before pruning older logs. Default: 5.",
    "default_indent": "Default indentation for JSON formatting (spaces per level).",
    "category": "Predefined logging categories for structured logging, providing identifiers and colors for different log levels."
}
