[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "requirements.dependencies"
version = "1.0.0"
description = "Structured Dependencies/Requirements for Python applications"
readme = "README.md"
authors = [{ name = "Eduardo Valdes", email = "emvaldes@hotmail.com" }]
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Homepage = "https://github.com/emvaldes/devops-workflow"
Repository = "https://github.com/emvaldes/devops-workflow"
