name: "Aggregate Pytest Results"
description: "Parses and summarizes pytest results into a structured JSON file"
author: "Eduardo Valdes"

inputs:
  artifact_name:
    description: "The artifact name containing test result XML files"
    required: true
    default: "pytest-results-*"

outputs:
  summary_json:
    description: "Path to the generated JSON summary file"
    value: "test_results.json"

env:
  GITHUB_SCRIPTS: ${{ github.workspace }}/.github/scripts

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Test Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: artifacts/  # Ensures test results go to the correct location

    - name: Run Summary Script
      run: |

        ./${{ env.GITHUB_SCRIPTS }}/aggregate-pytest-results.shell ;

    - name: Verify JSON Output
      run: |

        if [[ ! -f ./${{ env.summary_json }} ]]; then
          echo -e "ERROR: No test results JSON generated!" ;
          exit 1 ;
        fi ;

        echo -e "Generated Test Summary JSON: " ;
        cat ./${{ env.summary_json }} | jq . ;

    - name: Upload JSON Summary
      uses: actions/upload-artifact@v4
      with:
        name: test-results-summary
        path: ${{ env.summary_json }}
