name: "Aggregate Pytest Results"
description: "Parses and summarizes pytest results into a structured JSON file"
author: "Eduardo Valdes"

inputs:
  artifact_name:
    description: "The artifact name containing test result XML files"
    required: true
    default: "pytest-results-*"

outputs:
  summary_json:
    description: "Path to the generated JSON summary file"
    value: "./test_results.json"

env:
  GITHUB_ACTION: ${{ github.workspace }}/.github/actions/test-summary

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Test Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: artifacts/  # ✅ Ensures test results go to the correct location

    - name: Ensure Shell Script is Executable
      shell: bash
      run: chmod +x ${{ env.GITHUB_ACTION }}/aggregate-test-results.shell

    - name: Run Summary Script
      shell: bash
      run: ./${{ env.GITHUB_ACTION }}/aggregate-test-results.shell

    - name: Verify JSON Output
      shell: bash
      run: |
        if [[ ! -f test_results.json ]]; then
          echo "❌ ERROR: No test results JSON generated!"
          exit 1
        fi
        echo "✅ Generated Test Summary JSON:"
        cat test_results.json | jq .

    - name: Upload JSON Summary
      uses: actions/upload-artifact@v4
      with:
        name: test-results-summary
        path: test_results.json
