name: "Aggregate Pytest Results"
description: "Parses and summarizes pytest results into a structured JSON file"
author: "Eduardo Valdes"

inputs:
  artifact_name:
    description: "The artifact name containing test result XML files"
    required: true
    default: "pytest-results-*"

outputs:
  summary_json:
    description: "Path to the generated JSON summary file"
    value: "./test_results.json"

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # ✅ Ensures the action runs with the latest repo contents

    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact_name }}  # ✅ Allows wildcard matching
        merge-multiple: true  # ✅ Merges multiple test result files into `artifacts/`

    - name: Ensure Shell Script is Executable
      shell: bash
      run: chmod +x .github/actions/test-summary/entrypoint.shell  # ✅ Prevents permission issues

    - name: Run summary script
      shell: bash
      run: .github/actions/test-summary/entrypoint.shell

    - name: Upload JSON Summary
      uses: actions/upload-artifact@v4
      with:
        name: test-results-summary
        path: test_results.json
