name: AppFlow-Tracer -> Tracing Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  dependencies:
    name: Install Required Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install Dependencies
        id: dependencies_install
        run: |
          echo "Running dependencies module to install missing packages..."
          python -m packages.requirements.dependencies

      - name: Run Dependencies Tests
        id: dependencies_tests
        run: |
          echo "Running Pytest for dependencies module..."
          pytest -v tests/requirements/dependencies

      - name: Show Installed Packages
        run: |
          echo "Running dependencies module to show installed packages..."
          python -m packages.requirements.dependencies --show-installed

  tracing:
    name: Run Tracing Module
    runs-on: ubuntu-latest
    needs: dependencies  # Ensures dependencies workflow completes successfully

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Run Tracing Tests
        id: tracing_tests
        run: |
          echo "Running Pytest for tracing module..."
          pytest -v tests/appflow_tracer/tracing

      - name: Run Tracing Module
        id: tracing_run
        run: |
          echo "Running tracing module to verify functionality..."
          python -m packages.appflow_tracer.tracing
