---
## File: module.extract-pytests.yaml

name: Extract PyTest Test-Functions
on:

  workflow_call:

    inputs:

      github_action:
        required: true
        type: string

    outputs:

      test_functions:
        description: "Extracted PyTest Functions"
        value: ${{ jobs.extract-pytests.outputs.test_functions }}

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    steps:

      - name: Validate Input Parameters
        id: validate_parameters
        run: |

          params=false ;
          error_header="Workflow: 'module.extract-pytests' cannot proceed without" ;

          [[ -z "${{ inputs.github_action }}" ]] && {
            echo -e "${error_header} a valid GitHub Action." ;
            invalid_params=true ;
          } ;

          [[ ${invalid_params} == true ]] && exit -1 ;

  extract-pytests:
    needs: validate-parameters
    runs-on: ubuntu-latest
    outputs:
      test_functions: ${{ steps.extract.outputs.tests }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Shell Script is Executable
        run: |
          chmod +x "${{ inputs.github_action }}/extract-pytest-functions.shell" ;

      - name: Extract Test Functions
        id: extract
        run: |
          "${{ inputs.github_action }}/extract-pytest-functions.shell" ;
          if ! jq -e . test_functions.json > /dev/null 2>&1; then
            echo -e "ERROR: test_functions.json is not valid JSON!" ;
            cat test_functions.json ;
            exit 1 ;
          fi ;
          TESTS=$( jq -c '.test_functions' test_functions.json ) ;
          echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
