---
## File: module.execute-module.yaml

name: Execute Target Package Module
on:

  workflow_call:

    inputs:

      package_location:
        required: true
        type: string
        default: ''

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.exectute-module",
          "params": {
            "package_location": {
              "Package Location": "${{ github.event.inputs.package_location }}"
            }
          }
        }

  execute-module:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS).python }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Verify requirements.txt Exists
        run: |
          if [[ ! -f requirements.txt ]]; then
            echo "ERROR: requirements.txt is missing!" ;
            exit 1 ;
          fi ;
          echo "requirements.txt found!" ;
          cat requirements.txt ;

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Reinstall Dependencies from Cache
        run: |
          python -m pip install --upgrade pip ;
          python -m pip install -r requirements.txt ;

      - name: Set PYTHONPATH to Repository Root
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV ;
          echo -e "PYTHONPATH set to: ${GITHUB_WORKSPACE}" ;

      - name: Convert Path & Execute Python Module
        run: |
          package_module=$( echo "${{ inputs.package_location }}" | sed 's/\//./g' ) ;
          echo "Executing Python module: ${package_module}" ;
          python -m $package_module ;
