---
## File: .github/workflows/module.running-pytests.yaml

name: Running PyTests Test Functions
on:

  workflow_call:

    inputs:

      test_functions:
        required: true
        type: string
        default: ''

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.running-pytests",
          "params": {
            "test_functions": {
              "PyTest Functions": ${{ toJson( fromJson( inputs.test_functions ) ) }}
            }
          }
        }

  running-pytests:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson( vars.PYTHON_VERSIONS ).python }}
        test_function: ${{ inputs.test_functions }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Restore Cached Dependencies (1st. iteration)
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
      #     restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Verify requirements.txt Exists
        run: |
          if [[ ! -f requirements.txt ]]; then
            echo -e "ERROR: requirements.txt is missing!" ;
            exit 1 ;
          fi ;
          echo -e "requirements.txt found!" ;
          cat requirements.txt ;

      - name: Reinstall Dependencies from Cache
        run: |
          python -m pip install --upgrade pip ;
          python -m pip install -r requirements.txt ;

      # - name: Run Pytest Function (1st. iteration)
      #   run: |
      #     pytest -v --junitxml=pytest-results.xml \
      #     "${{ inputs.pytests_location }}/test_dependencies.py::${{ matrix.test_function }}" ;

      - name: Run Pytest Functions for Each File
        run: |
          # Enable Bash debugging
          set -x

          # Extract the raw JSON from the matrix (stringified JSON)
          RAW_JSON='${{ matrix.test_function }}'

          # Debug: Show raw JSON
          echo "DEBUG: Raw JSON input from GitHub Actions:"
          echo "$RAW_JSON"

          # Parse JSON properly using jq
          TEST_FILE=$(echo "$RAW_JSON" | jq -r 'keys[]')

          # Debug: Show extracted test file
          echo "DEBUG: Test file to process: $TEST_FILE"

          # Ensure FILE is not empty
          if [[ -z "$TEST_FILE" ]]; then
            echo "ERROR: No test file found. Skipping."
            exit 0
          fi

          # Extract test functions for the file
          TEST_FUNCTIONS=$(echo "$RAW_JSON" | jq -r --arg FILE "$TEST_FILE" '.[$FILE][]')

          # Debug: Show extracted test functions
          echo "DEBUG: Extracted test functions for $TEST_FILE: $TEST_FUNCTIONS"

          # Ensure there are test functions to run
          if [[ -z "$TEST_FUNCTIONS" ]]; then
            echo "ERROR: No test functions found in $TEST_FILE. Skipping."
            exit 0
          fi

          # Debug: Show pytest command before execution
          echo "DEBUG: Running command: pytest -v --junitxml=pytest-results.xml $TEST_FILE::$(echo "$TEST_FUNCTIONS" | tr ' ' '::')"

          # Run pytest
          pytest -v --junitxml=pytest-results.xml "$TEST_FILE"::$(echo "$TEST_FUNCTIONS" | tr ' ' '::')

      # - name: Upload Test Results (1st. iteration)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
      #     path: pytest-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
          path: pytest-results.xml

      # - name: Debug - List Uploaded Artifacts (1st. iteration)
      #   run: |
      #     echo -e "Listing uploaded artifacts..." ;
      #     find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
      #     echo -e "Checking artifact storage location..." ;

      - name: Debug - List Uploaded Artifacts
        run: |
          echo -e "Listing uploaded artifacts..." ;
          find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
          echo -e "Checking artifact storage location..." ;
