---
## File: .github/workflows/module.validate-parameters.yaml

name: Validate Parameters
on:

  workflow_call:

    inputs:

      workflow_inputs:
        description: "Workflow's input-parameters (JSON string)."
        required: true
        type: string

  # push:
  #   branches:
  #     - master
  #     - functional
  #   paths:
  #     - .github/workflows/**
  #     - .github/actions/**
  #
  #   pull_request:
  #     branches:
  #       - master

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    outputs:
      validated_params: ${{ steps.set-params.outputs.validated_params }}
    steps:

      - name: Checkout Repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Validate Input Parameters
        id: validate_parameters
        env:
          github_action: "${{ github.workspace }}/.github/actions/test-summary"
        shell: bash
        run: |

          echo -e ${{ toJson( inputs.workflow_inputs ) }} ;
          validated_parameters=$(
            ${{ env.github_action }}/validate-input-parameters.shell \
            --json='${{ toJson( inputs.workflow_inputs ) }}'
          )
          echo "validated_params=$validated_parameters" >> "$GITHUB_OUTPUT"
