---
## File: module.aggregate-results.yaml

name: Aggregate PyTests Results
on:

  workflow_call:

    inputs:

      github_action:
        required: true
        type: string

      artifacts_location:
        required: true
        type: string
        default: "artifacts"

    outputs:

      aggregated_results:
        description: "Signaling PyTest Results Aggregation completion"
        value: ${{ jobs.aggregate-pytest-results.outputs.aggregated_results }}

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    steps:

      - name: Validate Input Parameters
        id: validate_parameters
        run: |

          if [[ -z "${{ inputs.github_action }}" ]]; then
            echo -e  "Error: '${{ env.GITHUB_WORKFLOW }}' cannot proceed without a valid GitHub Action." ;
            exit 1 ;
          fi ;

          if [[ -z "${{ inputs.artifacts_location }}" ]]; then
            echo -e  "Error: '${{ env.GITHUB_WORKFLOW }}' cannot proceed without a valid Artifacts Location." ;
            exit 1 ;
          fi ;

  aggregate-pytest-results:
    needs: valdiate-parameters
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: "true"
    steps:

      - name: Install System Packages
        id: installing_system_packages
        run: |
          sudo apt-get update --yes ;
          sudo apt-get install tree jq --yes ;

      - name: Checkout Repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Ensure Script is Executable
        id: executable_script
        run: |
          chmod +x ${{ inputs.github_action }}/inspect-artifacts-state.shell ;

      - name: Locating Artifacts
        id: locating_artifacts
        run: |
          ${{ inputs.github_action }}/inspect-artifacts-state.shell ;

      - name: Download All Test Artifacts
        id: downloading_artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.artifacts_location }}/

      - name: Verify Downloaded Artifacts
        id: verifying_artifacts
        run: |
          echo -e "Listing downloaded artifacts..." ;
          tree -FCla --prune -I .git ./artifacts 2>/dev/null ;

      - name: Aggregate Pytest Results
        id: aggregating_results
        run: |
          ${{ inputs.github_action }}/aggregate-pytest-results.shell ;

      - name: Configure Workflow Status
        id: workflow_status
        run: |
          echo "aggregated_results=true" >> $GITHUB_ENV
          echo "Aggregate Results - GitHub Environment:\n${GITHUB_ENV}" ;
