---
## File: module.extract-pytests.yaml

name: Extract PyTest Test-Functions
on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string

      github_action:
        required: true
        type: string

    outputs:

      test_functions:
        description: "Extracted PyTest Functions"
        value: ${{ jobs.extract-pytests.outputs.test_functions }}

jobs:

  pytests-location:
    runs-on: ubuntu-latest
    steps:

      - name: Check PyTests Location
        id: pytests_location
        run: |
          if [[ -z "${{ inputs.pytests_location }}" ]]; then
            echo -en "Error: inputs.pytests_location must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid PyTests Location." ;
            exit 1 ;
          fi ;

  github-action:
    runs-on: ubuntu-latest
    steps:

      - name: Check GitHub Action
        id: github_action
        run: |
          if [[ -z "${{ inputs.github_action }}" ]]; then
            echo -en "Error: inputs.github_action must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid GitHub Action." ;
            exit 1 ;
          fi ;

  extract-pytests:
    needs: [pytests-location, github-action]
    runs-on: ubuntu-latest
    outputs:
      test_functions: ${{ steps.extract.outputs.tests }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Shell Script is Executable
        run: |
          chmod +x "${{ inputs.github_action }}/extract-pytest-functions.shell" ;

      - name: Extract Test Functions
        id: extract
        run: |
          "${{ inputs.github_action }}/extract-pytest-functions.shell" ;
          if ! jq -e . test_functions.json > /dev/null 2>&1; then
            echo -e "ERROR: test_functions.json is not valid JSON!" ;
            cat test_functions.json ;
            exit 1 ;
          fi ;
          TESTS=$( jq -c '.test_functions' test_functions.json ) ;
          echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
