---
## File: .github/workflows/module.running-pytests.yaml

name: Running PyTests Test Functions
on:

  workflow_call:

    inputs:

      test_functions:
        required: true
        type: string

      pytest:
        required: false
        type: string

jobs:

  workflow:

    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "module.running-pytests",
          "inputs": {
            "test_functions": {
              "id": "PyTest Functions",
              "value": ${{ toJson( fromJson( inputs.test_functions ) ) }}
            },
            "pytest": {
              "id": "Workflow Parameters", "value": ${{ inputs.pytest }}
            }
          }
        }

  parameters:

    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Module - Running-PyTests (Parameters)
        id: workflow_parameters
        run: |

          echo -e "PyTests Location: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest.params.pytests_location }}" ;
            echo -e "PyTests Resources: ${{ fromJson(
              needs.workflow.outputs.validated ).pytest.params.pytests_resources }}" ;
          echo -e "PyTest Functions: ${{ fromJson(
            needs.workflow.outputs.validated ).test_functions }}" ;

  # Experimental Cutter Matrix Using pytest_files.json
  pytest-files:

    needs: [ workflow, parameters ]
    runs-on: ubuntu-latest
    outputs:
      pytest_files: ${{ steps.extract.outputs.pytest_files }}
    steps:

      - name: Listing Current Environment Variables
        id: current_variables
        run: |
          env | sort ;

      - name: Listing Shell/Environment Variables
        id: shell_variables
        run: |
          set ;

      - name: Importing PyTest Files/Functions
        id: importing_resources
        run:

          cat ./pytest_files.json ;
          cat ./test_functions.json ;

  running-pytests:

    needs: [ workflow, parameters, pytest-files ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson( vars.PYTHON_VERSIONS ).python }}
        test_function: ${{ fromJson( inputs.test_functions ) }}
    env:
      pytests_location: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest.params.pytests_location }}
      pytests_resources: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest.params.pytests_resources }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Packages
        id: installing_system_packages
        run: |

          sudo apt-get update --yes ;
          sudo apt-get install tree jq --yes ;

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Listing Entire Project
        id: listing_project
        run: |

          tree -FCla --prune -I .git ${{ github.workspace }} ;

      - name: Verify requirements.txt Exists
        run: |

          if [[ ! -f requirements.txt ]]; then
              echo -e "ERROR: requirements.txt was not found!" ;
              exit 1 ;
            else  echo -e "requirements.txt found!" ;
              cat requirements.txt ;
          fi ;

      - name: Reinstall Dependencies from Cache
        run: |

          python -m pip install --upgrade pip ;
          python -m pip install -r requirements.txt ;

      - name: Run Pytest Function
        run: |

          pytest -v --junitxml=pytest-results.xml \
          "${{ env.pytests_location }}/${{ env.pytests_resources }}::${{ matrix.test_function }}" ;

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
          path: pytest-results.xml

      - name: Debug - List Uploaded Artifacts
        run: |

          echo -e "Listing uploaded artifacts..." ;
          find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
          echo -e "Checking artifact storage location..." ;
