---
## File: .github/workflows/module.running-pytests.yaml

name: Running PyTests Test Functions
on:

  workflow_call:

    inputs:

      test_functions:
        required: true
        type: string
        default: ''

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.running-pytests",
          "params": {
            "test_functions": {
              "PyTest Functions": ${{ toJson( fromJson( inputs.test_functions ) ) }}
            }
          }
        }

  extract-testfiles:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.extract.outputs.test_files }}
    steps:
      - name: Extract Test Files
        id: extract
        run: |

          echo -en "Extracting test files from inputs ..." ;

          TEST_FILES=$( echo '${{ inputs.test_functions }}' | jq -c 'keys' ) ;
          echo -e " done." ;
          echo -e "PyTests Files: ${TEST_FILES}" ;

          echo "test_files=$TEST_FILES" >> $GITHUB_OUTPUT ;

  running-pytests:
    needs: extract-testfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson( vars.PYTHON_VERSIONS ).python }}
        # test_function: ${{ fromJson( inputs.test_functions ) }}
        test_file: ${{ fromJson( needs.extract-testfiles.outputs.test_files ) }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
          # restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-
          key: pip-${{ matrix.python-version }}-${{ matrix.test_file }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_file }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Verify requirements.txt Exists
        run: |
          if [[ ! -f requirements.txt ]]; then
            echo -e "ERROR: requirements.txt is missing!" ;
            exit 1 ;
          fi ;
          echo -e "requirements.txt found!" ;
          cat requirements.txt ;

      - name: Reinstall Dependencies from Cache
        run: |
          python -m pip install --upgrade pip ;
          python -m pip install -r requirements.txt ;

      - name: Run Pytest Function
        run: |

          # pytest -v --junitxml=pytest-results.xml \
          # "${{ inputs.pytests_location }}/test_dependencies.py::${{ matrix.test_function }}" ;

          set -x
          FILE="${{ matrix.test_file }}"
          TEST_FUNCTIONS=$(echo '${{ inputs.test_functions }}' | jq -r --arg FILE "$FILE" '.[$FILE][]')

          if [[ -z "$TEST_FUNCTIONS" ]]; then
            echo "No test functions found in $FILE. Skipping."
            exit 0
          fi

          echo "Running tests in: $FILE"
          echo "Test functions: $TEST_FUNCTIONS"

          # pytest -v --junitxml=pytest-results.xml $FILE::$(echo "$TEST_FUNCTIONS" | tr ' ' '::')
          echo "$TEST_FUNCTIONS" | awk -v file="$FILE" '{for(i=1; i<=NF; i++) print file "::" $i}' | xargs -n 1 pytest -v --junitxml=pytest-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          # name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_file }}
          path: pytest-results.xml

      - name: Debug - List Uploaded Artifacts
        run: |
          echo -e "Listing uploaded artifacts..." ;
          find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
          echo -e "Checking artifact storage location..." ;
