---
## File: .github/workflows/module.extract-pytests.yaml

name: Extract PyTest Test-Functions
on:

  workflow_call:

    inputs:

      pytest_mapping:
        required: false
        type: string
        # default: 'pytest_functions.json'

      pytest:
        required: false
        type: string

    outputs:

      pytest_files:
        description: "Extracted PyTest Modules"
        value: ${{ jobs.extract-pytests.outputs.pytest_files }}

      test_functions:
        description: "Extracted PyTest Functions"
        value: ${{ jobs.extract-pytests.outputs.test_functions }}

jobs:

  workflow:

    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "module.extract-pytests",
          "inputs": {
            "pytest_mapping": {
              "id": "PyTest Mapping",
              "value": "${{ inputs.pytest_mapping }}",
              "default": "${{ vars.PYTEST_MAPPING }}"
            },
            "pytest": {
              "id": "Workflow Parameters", "value": ${{ inputs.pytest }}
            }
          }
        }

  parameters:

    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Module - Extract-PyTests (Parameters)
        id: workflow_parameters
        run: |

          echo "PyTest Mapping: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest_mapping }}" ;
          echo -e "PyTests Location: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest.params.pytests_location }}" ;
          echo -e "Project Scripts: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest.params.project_scripts }}" ;
          echo -e "PyTest Mapping: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest_mapping }}" ;

  extract-pytests:

    needs: [ workflow, parameters ]
    runs-on: ubuntu-latest
    outputs:
      pytest_files: ${{ steps.extract.outputs.pytest_files }}
      test_functions: ${{ steps.extract.outputs.test_functions }}
    env:
      project_scripts: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest.params.project_scripts }}
      pytests_location: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest.params.pytests_location }}
      pytest_mapping: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest_mapping }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Test Functions
        id: extract
        shell: bash
        run: |

          set -x ;

          extracted=$(
            ${{ env.project_scripts }}/extract-pytest-functions.shell \
            --pytests-location="${{ env.pytests_location }}" \
            --scripts-location="${{ env.project_scripts }}" \
            --output-filename="${{ env.pytest_mapping }}"
          ) ; # echo -e "Extracted Parameters:\n${extracted}" ;

          ## Validate Test-Functions JSON before proceeding
          if [[ -e ${{ env.pytest_mapping }} ]]; then
                jq -e . ${{ env.pytest_mapping }} 2>&1>/dev/null ;
                status=$?; #echo -e "Status: ${status}" ;
                if [[ ${status} -gt 0 ]]; then
                    echo -e "Configuration: Invalid JSON '${{ env.pytest_mapping }}' object!" ;
                    exit 1 ;
                  else  echo -e "\nPyTest Functions JSON configuration" ;
                    ls -al ${{ env.pytest_mapping }} ;
                    cat ${{ env.pytest_mapping }} ;
                    TEST_FUNCTIONS=$(
                      jq -c '.test_functions' ${{ env.pytest_mapping }}
                    ) ;
                    echo -e "test_functions=$TEST_FUNCTIONS" >> "$GITHUB_OUTPUT" ;
                fi ;
            else  echo -e "Warning: '${{ env.pytest_mapping }}' is missing/not-found!" ;
          fi ;

          ## Validate Test-Modules JSON before proceeding
          pytest_files="pytest_files.json" ;
          if [[ -e ${pytest_files} ]]; then
                  jq -e . ${pytest_files} 2>&1>/dev/null ;
                  status=$?; #echo -e "Status: ${status}" ;
                  if [[ ${status} -gt 0 ]]; then
                      echo -e "Configuration: '${pytest_files}' is not valid JSON object!" ;
                      exit 1 ;
                    else  echo -e "\nPyTest Files JSON configuration" ;
                      ls -al ${pytest_files} ;
                      cat ${pytest_files} ;
                      # PYTEST_FILES=$( jq -c 'keys' ${pytest_files} ) ;
                      PYTEST_FILES=$( jq -c . ${pytest_files} ) ;
                      echo "pytest_files=$PYTEST_FILES" >> $GITHUB_OUTPUT ;
                  fi ;
            else  echo -e "Warning: ${pytest_files} is missing/not-found!" ;
          fi ;
