---
## File: module.aggregate-results.yaml

name: Aggregate PyTests Results
on:

  workflow_call:

    inputs:

      GITHUB_ACTION:
        required: true
        type: string

      ARTIFACTS_DIR:
        required: true
        type: string

jobs:

  aggregate-test-results:
    runs-on: ubuntu-latest
    steps:

      - name: Install System Packages
        run: |
          sudo apt-get update --yes ;
          sudo apt-get install tree jq --yes ;

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Debug Script is Executable
        run: |
          chmod +x ${{ inputs.GITHUB_ACTION }}/debug-artifacts-state.shell ;

      - name: Debug - Locate Artifacts
        run: |
          ${{ inputs.GITHUB_ACTION }}/debug-artifacts-state.shell ;

      - name: Download All Test Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.ARTIFACTS_DIR }}/

      - name: Verify Downloaded Artifacts
        run: |
          echo -e "Listing downloaded artifacts..." ;
          tree -FCla --prune -I .git ./artifacts 2>/dev/null ;

      - name: Aggregate Pytest Results
        run: |
          ${{ inputs.GITHUB_ACTION }}/aggregate-test-results.shell ;

      - name: Listing Entire Project
        run: |
          tree -FCla --prune -I .git ${{ github.workspace }} ;
          # cat ${{ inputs.ARTIFACTS_DIR }}/test_functions.log ;
          # cat ${{ inputs.ARTIFACTS_DIR }}/test_results.json ;
