---
## File: .github/workflows/module.running-pytests.yaml

name: Running PyTests Test Functions
on:

  workflow_call:

    inputs:

      test_functions:
        required: true
        type: string
        default: ''

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.running-pytests",
          "params": {
            "test_functions": {
              "PyTest Functions": ${{ toJson( fromJson( inputs.test_functions ) ) }}
            }
          }
        }

  running-pytests:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson( vars.PYTHON_VERSIONS ).python }}
        # test_function: ${{ inputs.test_functions }}
        test_files: ${{ toJson( keys( fromJson( inputs.test_functions ) ) ) }}
        test_functions: ${{ toJson( fromJson( inputs.test_functions )[matrix.test_file] ) }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Restore Cached Dependencies (1st. iteration)
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
      #     restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Verify requirements.txt Exists
        run: |
          if [[ ! -f requirements.txt ]]; then
            echo -e "ERROR: requirements.txt is missing!" ;
            exit 1 ;
          fi ;
          echo -e "requirements.txt found!" ;
          cat requirements.txt ;

      - name: Reinstall Dependencies from Cache
        run: |
          python -m pip install --upgrade pip ;
          python -m pip install -r requirements.txt ;

      # - name: Run Pytest Function (1st. iteration)
      #   run: |
      #     pytest -v --junitxml=pytest-results.xml \
      #     "${{ inputs.pytests_location }}/test_dependencies.py::${{ matrix.test_function }}" ;

      # - name: Run Pytest Function (2nd. iteration)
      #   run: |
      #     set -x  # Enable debugging
      #
      #     FILE="${{ matrix.test_file }}"
      #     FUNCTION="${{ matrix.test_function }}"
      #
      #     echo "DEBUG: Running test file: $FILE"
      #     echo "DEBUG: Running test function: $FUNCTION"
      #
      #     # Run only the specified function
      #     pytest -v --junitxml=pytest-results.xml "$FILE::$FUNCTION"

      - name: Run Pytest Function
        run: |
          # Enable debugging
          set -x

          # Extract test file and function from matrix
          FILE="${{ matrix.test_file }}"
          FUNCTION="${{ matrix.test_function }}"

          # Debugging: Show the test file and function being processed
          echo "DEBUG: Running test file: $FILE"
          echo "DEBUG: Running test function: $FUNCTION"

          # Ensure FILE is not empty
          if [[ -z "$FILE" ]]; then
            echo "ERROR: No test file found. Skipping."
            exit 1
          fi

          # Ensure FUNCTION is not empty
          if [[ -z "$FUNCTION" ]]; then
            echo "ERROR: No test function found. Skipping."
            exit 1
          fi

          # Read the full JSON input to confirm correctness
          RAW_JSON='${{ inputs.test_functions }}'

          # Debugging: Show full JSON input
          echo "DEBUG: Full JSON input from GitHub Actions:"
          echo "$RAW_JSON" | jq .

          # Validate if the function exists in the given file
          FUNCTION_EXISTS=$(echo "$RAW_JSON" | jq -r --arg FILE "$FILE" --arg FUNCTION "$FUNCTION" 'if .[$FILE] | index($FUNCTION) then "yes" else "no" end')

          if [[ "$FUNCTION_EXISTS" != "yes" ]]; then
            echo "ERROR: Function $FUNCTION not found in file $FILE. Skipping."
            exit 1
          fi

          # Debugging: Show pytest command before execution
          echo "DEBUG: Running pytest: pytest -v --junitxml=pytest-results.xml $FILE::$FUNCTION"

          # Run pytest
          pytest -v --junitxml=pytest-results.xml "$FILE::$FUNCTION"

      # - name: Upload Test Results (1st. iteration)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
      #     path: pytest-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
          path: pytest-results.xml

      # - name: Debug - List Uploaded Artifacts (1st. iteration)
      #   run: |
      #     echo -e "Listing uploaded artifacts..." ;
      #     find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
      #     echo -e "Checking artifact storage location..." ;

      - name: Debug - List Uploaded Artifacts
        run: |
          echo -e "Listing uploaded artifacts..." ;
          find $GITHUB_WORKSPACE -type f -name "*.xml" || echo -e "No test result files found." ;
          echo -e "Checking artifact storage location..." ;
