---
## File: .github/workflows/module.validate-parameters.yaml

name: Validate Parameters
on:

  workflow_call:

    inputs:

      workflow_inputs:
        description: "Workflow's input-parameters (JSON string)."
        required: true
        type: string

  # push:
  #   branches:
  #     - master
  #     - functional
  #   paths:
  #     - .github/workflows/**
  #     - .github/actions/**
  #
  #   pull_request:
  #     branches:
  #       - master

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.validate_parameters.outputs.validated }}
    steps:

      - name: Checkout Repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Validate Input Parameters
        id: validate_parameters
        env:
          github_action: "${{ github.workspace }}/.github/actions/test-summary"
        shell: bash
        run: |

          set -x ;

          validated_parameters=$(
            ${{ env.github_action }}/validate-input-parameters.shell \
            --json='${{ inputs.workflow_inputs }}'
          ) ;
          validated="$( jq -c . <<< "${validated_parameters}" )"
          echo "Validated Params:\n${validated}" ;
          echo "validated=$validated" >> "$GITHUB_OUTPUT" ;
