---
## File: .github/workflows/module.aggregate-results.yaml

name: Aggregate PyTests Results
on:

  workflow_call:

    inputs:

      github_scripts:
        required: true
        type: string

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

      workflow_params:
        required: false
        type: string

    outputs:

      aggregated_results:
        description: "Signaling PyTest Results Aggregation completion"
        value: ${{ jobs.aggregate-pytest-results.outputs.aggregated_results }}

jobs:

  workflow:

    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "module.aggregate-results",
          "params": {
            "github_scripts": {
              "id": "GitHub Scripts",
              "value": "${{ inputs.github_scripts }}"
            },
            "artifacts_location": {
              "id": "Artifacts Location",
              "value": "${{ inputs.artifacts_location }}"
            }
          }
        }

  parameters:

    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Module - Aggregate-Results (Parameters)
        id: workflow_parameters
        run: |

          echo -e "GitHub Action: ${{ fromJson(
            needs.workflow.outputs.validated ).github_scripts }}" ;
          echo -e "Artifacts Location: ${{ fromJson(
            needs.workflow.outputs.validated ).artifacts_location }}" ;

          workflow_params: ${{ needs.workflow.outputs.validated }}

  aggregate-pytest-results:

    needs: [workflow, parameters]
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: "true"
    env:
      github_scripts: >-
        ${{ fromJson( needs.workflow.outputs.validated ).github_scripts }}
      artifacts_location: >-
        ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}
    steps:

      - name: Install System Packages
        id: installing_system_packages
        run: |

          sudo apt-get update --yes ;
          sudo apt-get install tree jq --yes ;

      - name: Checkout Repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Locating Artifacts
        id: locating_artifacts
        run: |

          ${{ env.github_scripts }}/inspect-artifacts-state.shell ;

      - name: Download All Test Artifacts
        id: downloading_artifacts
        uses: actions/download-artifact@v4
        with:
          path: >-
            ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}/

      - name: Verify Downloaded Artifacts
        id: verifying_artifacts
        run: |

          echo -e "Listing downloaded artifacts..." ;
          tree -FCla --prune -I .git ./artifacts 2>/dev/null ;

      - name: Aggregate Pytest Results
        id: aggregating_results
        run: |

          ${{ env.github_scripts }}/aggregate-pytest-results.shell ;

      - name: Configure Workflow Status
        id: workflow_status
        run: |

          echo "aggregated_results=true" >> $GITHUB_ENV
          echo "Aggregate Results - GitHub Environment:\n${GITHUB_ENV}" ;

      - name: Listing Entire Project
        id: listing_project
        run: |

          tree -FCla --prune -I .git ${{ github.workspace }} ;
