---
## File: module.extract-pytests.yaml

name: Extract PyTest Test-Functions
on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string
        default: ''

      github_action:
        required: true
        type: string
        default: ''

    outputs:

      test_functions:
        description: "Extracted PyTest Functions"
        value: ${{ jobs.extract-pytests.outputs.test_functions }}

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.extract-pytests",
          "params": {
            "pytests_location": {
              "PyTest Location": "${{ inputs.pytests_location }}"
            },
            "github_action": {
              "GitHub Action": "${{ inputs.github_action }}"
            }
          }
        }

  extract-pytests:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    outputs:
      test_functions: ${{ steps.extract.outputs.tests }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Shell Script is Executable
        run: |
          chmod +x "${{ inputs.github_action }}/extract-pytest-functions.shell" ;

      - name: Extract Test Functions
        id: extract
        run: |

          ${{ inputs.github_action }}/extract-pytest-functions.shell \
            --pytests-location="${{ inputs.pytests_location }}" \
            --output-filename="${{ inputs.output_filename }}" \
            --scripts-location="${{ inputs.github_action }}" ;

          if ! jq -e . test_functions.json > /dev/null 2>&1; then
            echo -e "ERROR: test_functions.json is not valid JSON!" ;
            cat test_functions.json ;
            exit 1 ;
          fi ;

          TESTS=$( jq -c '.test_functions' test_functions.json ) ;
          echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
