---
## File: .github/workflows/module.aggregate-results.yaml

name: Aggregate PyTests Results
on:

  workflow_call:

    inputs:

      github_action:
        required: true
        type: string

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

    outputs:

      aggregated_results:
        description: "Signaling PyTest Results Aggregation completion"
        value: ${{ jobs.aggregate-pytest-results.outputs.aggregated_results }}

  # push:
  #   branches:
  #     - master
  #     - functional
  #   paths:
  #     - .github/workflows/**
  #     - .github/actions/**
  #
  #   pull_request:
  #     branches:
  #       - master

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "module.aggregate-results",
          "params": {
            "github_action": {
              "id": "GitHub Action",
              "value": "${{ inputs.github_action }}"
            },
            "artifacts_location": {
              "id": "Artifacts Location",
              "value": "${{ inputs.artifacts_location }}"
            }
          }
        }

  testing:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Testing Workflow Parameters
        id: workflow_parameters
        run: |

          echo "GitHub Action: ${{ fromJson( needs.workflow.outputs.validated ).github_action }}"
          echo "Artifacts Location: ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}"

  aggregate-pytest-results:
    needs: [workflow, testing]
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: "true"
    steps:

      - name: Install System Packages
        id: installing_system_packages
        run: |
          sudo apt-get update --yes ;
          sudo apt-get install tree jq --yes ;

      - name: Checkout Repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Locating Artifacts
        id: locating_artifacts
        run: |

          ${{ fromJson( needs.workflow.outputs.validated ).github_action }}/inspect-artifacts-state.shell ;

      - name: Download All Test Artifacts
        id: downloading_artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}/

      - name: Verify Downloaded Artifacts
        id: verifying_artifacts
        run: |
          echo -e "Listing downloaded artifacts..." ;
          tree -FCla --prune -I .git ./artifacts 2>/dev/null ;

      - name: Aggregate Pytest Results
        id: aggregating_results
        run: |

          ${{ fromJson( needs.workflow.outputs.validated ).github_action }}/aggregate-pytest-results.shell ;

      - name: Configure Workflow Status
        id: workflow_status
        run: |
          echo "aggregated_results=true" >> $GITHUB_ENV
          echo "Aggregate Results - GitHub Environment:\n${GITHUB_ENV}" ;

      - name: Listing Entire Project
        id: listing_project
        run: |
          tree -FCla --prune -I .git ${{ github.workspace }} ;
