---
## File: .github/workflows/module.validate-parameters.yaml

name: Validate Parameters
on:

  workflow_call:

    inputs:

      workflow_inputs:
        description: "Workflow's input-parameters (JSON string)."
        required: true
        type: string

env:
  github_actions: "${{ github.workspace }}/.github/actions"

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Input Parameters
        env:
          github_action: "${{ env.github_actions }}/test-summary"
        shell: bash
        run: |

          echo -e ${{ toJson( inputs.workflow_inputs ) }} ;

          ${{ env.github_action }}/validate-input-params.shell \
          --json=${{ toJson( inputs.workflow_inputs ) }} ;
