---
## File: pkgs.module-dependencies.yaml

name: Requirements - Dependencies Module
run-name: ${{ github.actor }} -> Dependencies Module

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: 'Directory containing PyTest files'
        required: false
        default: 'tests/requirements/dependencies'

      package_location:
        description: 'Directory containing package files'
        required: false
        default: 'packages/requirements/dependencies'

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  install-packages:
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      package_location: ${{ inputs.package_location }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_location: ${{ inputs.pytests_location }}
      package_location: ${{ inputs.package_location }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_location: ${{ inputs.package_location }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
