---
## File: pkgs.module-dependencies.yaml

name: Requirements - Dependencies Module
run-name: ${{ github.actor }} -> Dependencies Module

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: 'Directory containing PyTest files'
        required: false
        type: string
        default: 'tests/requirements/dependencies'

      package_location:
        description: 'Directory containing package files'
        required: false
        type: string
        default: 'packages/requirements/dependencies'

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    steps:

      - name: Validate Input Parameters
        id: validate_parameters
        run: |

          # invalid_params=false ;
          # error_header="Workflow: 'pytest.module-dependencies' cannot proceed without" ;
          #
          # [[ -z "${{ github.event.inputs.pytests_location }}" ]] && {
          #   echo -e "${error_header} a valid PyTest Location." ;
          #   invalid_params=true ;
          # } ;
          # [[ -z "${{ github.event.inputs.package_location }}" ]] && {
          #   echo -e "${error_header} a valid Package Location." ;
          #   invalid_params=true ;
          # } ;
          #
          # [[ ${invalid_params} == true ]] && exit 1 ;

          invalid_params=false
          error_header="Workflow: 'pytest.module-dependencies' cannot proceed without a valid"

          # Define your inputs with human-readable labels.
          declare -A inputs=(
            ["PyTest Location"]="${{ github.event.inputs.pytests_location }}"
            ["Package Location"]="${{ github.event.inputs.package_location }}"
          )

          # Iterate over the inputs.
          for label in "${!inputs[@]}"; do
            if [[ -z "${inputs[$label]}" ]]; then
              echo -e "${error_header} ${label}."
              invalid_params=true
            fi
          done

          # Exit with error if any input is invalid.
          [[ "${invalid_params}" == "true" ]] && exit 1

  install-packages:
    needs: validate-parameters
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      package_location: ${{ inputs.package_location }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_location: ${{ inputs.pytests_location }}
      package_location: ${{ inputs.package_location }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_location: ${{ inputs.package_location }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
