---
## File: pkgs.dependencies-module.yaml

name: Requirements - Dependencies Module
run-name: ${{ github.actor }} -> Dependencies Module

on:

  workflow_dispatch:

    inputs:

      pytests_dir:
        description: 'Directory containing PyTest files'
        required: false
        default: 'tests/requirements/dependencies'

      package_path:
        description: 'Directory containing package files'
        required: false
        default: 'packages/requirements/dependencies'

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  install-packages:
      uses: ./.github/workflows/module.install-packages.yaml
      with:
        package_path: ${{ inputs.package_path }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.dependencies-matrix.yaml
    with:
      pytests_dir: ${{ inputs.pytests_dir }}
      package_path: ${{ inputs.package_path }}
    outputs:
      aggregated_results: ${{ steps.aggregate-pytest-results.outputs.aggregated_results }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results == 'true'
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_path: ${{ inputs.package_path }}
