---
## File: .github/workflows/pkgs.module-tracing.yaml

name: Pipeline - AppFlow-Tracer/Tracing
run-name: ${{ github.actor }} -> Tracer/Tracing

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: "PyTests Files Directory"
        required: false
        type: string
        default: "tests/appflow_tracer/tracing"

      pytests_resources:
        description: "PyTests Target Resources"
        required: false
        type: string
        default: "test_tracing.py"

      package_location:
        description: "Packages/Modules Directory"
        required: false
        type: string
        default: "packages/appflow_tracer/tracing"

      project_scripts:
        description: "Target Project Scripts Path"
        required: false
        type: string
        default: ".github/scripts"

  push:
    branches:
      - master
      - functional
    paths:
      - .github/workflows/**
      - .github/actions/**
      - .github/scripts/**

    pull_request:
      branches:
        - master

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "pkgs.module-tracing",
          "inputs": {
            "pytests_location": {
              "id": "PyTest Location",
              "value": "${{ github.event.inputs.pytests_location }}",
              "default": "${{ vars.TRACING_PYTESTS }}"
            },
            "pytests_resources": {
              "id": "PyTests Resources",
              "value": "${{ github.event.inputs.pytests_resources }}",
              "default": "${{ vars.TRACING_RESOURCES }}"
            },
            "package_location": {
              "id": "Package Location",
              "value": "${{ github.event.inputs.package_location }}",
              "default": "${{ vars.TRACING_PACKAGE }}"
            },
            "project_scripts": {
              "id": "Project Scripts",
              "value": "${{ github.event.inputs.project_scripts }}",
              "default": "${{ vars.PROJECT_SCRIPTS }}"
            }
          }
        }
    env:

  parameters:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Packages - Module-Tracing (Parameters)
        id: workflow_parameters
        run: |

          echo -e "Workflow Parameters: ${{ needs.workflow.outputs.validated }}" ;

  install-packages:
    needs: [ workflow, parameters ]
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      packages: "packages/requirements/dependencies"

  pytests-module:
    needs: [ workflow, parameters, install-packages ]
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      params: ${{ needs.workflow.outputs.validated }}

  execute-module:
    needs: [ workflow, parameters, pytests-module ]
    # if: needs.pytests-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      params: ${{ needs.workflow.outputs.validated }}

  tracing-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed - Tracer/Tracing Workflow
        id: tracing_workflow
        run: |

          echo -e "Completed - Tracer/Tracing Workflow" ;
