---
## File: pkgs.module-dependencies.yaml

name: Requirements - Dependencies Module
run-name: ${{ github.actor }} -> Dependencies Module

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: 'Directory containing PyTest files'
        required: false
        type: string
        default: 'tests/requirements/dependencies'

      package_location:
        description: 'Directory containing package files'
        required: false
        type: string
        default: 'packages/requirements/dependencies'

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

env:
  github_action: ".github/actions/test-summary"

jobs:

  validate-parameters:
    runs-on: ubuntu-latest
    steps:

      - name: Validate Input Parameters
        id: validate_parameters
        run: |

          ## Define your inputs with human-readable labels.
          declare -A workflow_inputs=(
            ["PyTest Location"]="${{ github.event.inputs.pytests_location }}"
            ["Package Location"]="${{ github.event.inputs.package_location }}"
          );
          workflow_name='pytest.module-dependencies';

          ./${{ env.github_action }}/validate-input-params.shell \
          workflow_inputs "${workflow_name}";

  install-packages:
    needs: validate-parameters
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      package_location: ${{ inputs.package_location }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_location: ${{ inputs.pytests_location }}
      package_location: ${{ inputs.package_location }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_location: ${{ inputs.package_location }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
