---
## File: .github/workflows/pkgs.module-dependencies.yaml

name: Pipeline - Requirements/Dependencies
run-name: ${{ github.actor }} -> Requirements/Dependencies

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: "PyTests Files Directory"
        required: false
        type: string
        # default: "tests/requirements/dependencies"

      pytests_resources:
        description: "PyTests Target Resources"
        required: false
        type: string
        # default: "test_dependencies.py"

      package_location:
        description: "Packages/Modules Directory"
        required: false
        type: string
        # default: "packages/requirements/dependencies"

      project_scripts:
        description: "Target Project Scripts Path"
        required: false
        type: string
        # default: ".github/scripts"

  push:
    branches:
      - master
      - functional
    paths:
      - .github/workflows/**
      - .github/actions/**
      - .github/scripts/**

    pull_request:
      branches:
        - master

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "pkgs.module-dependencies",
          "inputs": {
            "pytests_location": {
              "id": "PyTest Location",
              "value": "${{ github.event.inputs.pytests_location }}",
              "default": "${{ vars.PYTESTS_DEPENDENCIES }}"
            },
            "pytests_resources": {
              "id": "PyTests Resources",
              "value": "${{ github.event.inputs.pytests_resources }}",
              "default": "${{ vars.DEPENDENCIES_RESOURCES }}"
            },
            "package_location": {
              "id": "Package Location",
              "value": "${{ github.event.inputs.package_location }}",
              "default": "${{ vars.DEPENDENCIES_PACKAGE }}"
            },
            "project_scripts": {
              "id": "Project Scripts",
              "value": "${{ github.event.inputs.project_scripts }}",
              "default": "${{ vars.PROJECT_SCRIPTS }}"
            }
          }
        }

  parameters:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Packages - Module-Dependencies (Parameters)
        id: workflow_parameters
        run: |

          echo -e "Workflow Parameters: ${{ needs.workflow.outputs.validated }}" ;

  install-packages:
    needs: [ workflow, parameters ]
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      packages: "${{
          github.event.inputs.package_location || vars.DEPENDENCIES_PACKAGE
        }}"

  pytests-module:
    needs: [ workflow, parameters, install-packages ]
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      params: ${{ needs.workflow.outputs.validated }}

  execute-module:
    needs: [ workflow, parameters, pytests-module ]
    # if: needs.pytests-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      params: ${{ needs.workflow.outputs.validated }}

  dependencies-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed - Dependencies Workflow
        id: dependencies_workflow
        run: |

          echo -e "Completed - Dependencies Workflow" ;
