---
## File: pkgs.module-tracing.yaml

name: AppFlow-Tracer - Tracing Module
run-name: ${{ github.actor }} -> Tracing Module

on:

  workflow_dispatch:

    inputs:

      pytests_dir:
        description: 'Directory containing PyTest files'
        required: false
        default: 'tests/appflow_tracer/tracing'

      package_path:
        description: 'Directory containing package files'
        required: false
        default: 'packages/appflow_tracer/tracing'

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  dependencies:
    uses: ./.github/workflows/pkgs.module-dependencies.yaml
    # with:
    #   package_path: ${{ inputs.package_path }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_dir: ${{ inputs.pytests_dir }}
      package_path: ${{ inputs.package_path }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_path: ${{ inputs.package_path }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
