---
## File: .github/workflows/pkgs.module-dependencies.yaml

name: Pipeline - Requirements/Dependencies
run-name: ${{ github.actor }} -> Requirements/Dependencies

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: "PyTest files Directory"
        required: false
        type: string
        default: "tests/requirements/dependencies"

      package_location:
        description: "Packages/Modules Directory"
        required: false
        type: string
        default: "packages/requirements/dependencies"

      github_action:
        description: "Target GitHub-Actions Path"
        required: false
        type: string
        default: ".github/actions/test-summary"

  push:
    branches:
      - master
      - functional
    paths:
      - .github/workflows/**
      - .github/actions/**

    pull_request:
      branches:
        - master

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "pkgs.module-dependencies",
          "params": {
            "pytests_location": {
              "id": "PyTest Location",
              "event": "${{ github.event.inputs.pytests_location }}",
              "value": "tests/requirements/dependencies"
            },
            "package_location": {
              "id": "Package Location",
              "event": "${{ github.event.inputs.package_location }}",
              "value": "packages/requirements/dependencies"
            },
            "github_action": {
              "id": "GitHub Action",
              "event": "${{ github.event.inputs.github_action }}",
              "value": ".github/actions/test-summary"
            }
          }
        }

  testing:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: Packages - Module-Dependencies (Parameters)
        id: workflow_parameters
        run: |

          echo "PyTests Location: ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}"
          echo "Package Location: ${{ fromJson( needs.workflow.outputs.validated ).package_location }}"
          echo "GitHub Action: ${{ fromJson( needs.workflow.outputs.validated ).github_action }}"

  install-packages:
    needs: [workflow, testing]
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      package_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).package_location }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}
      package_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).package_location }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).package_location }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
