---
## File: .github/workflows/pkgs.module-dependencies.yaml

name: Pipeline - Requirements/Dependencies
run-name: ${{ github.actor }} -> Requirements/Dependencies

on:

  workflow_dispatch:

    inputs:

      pytests_location:
        description: "PyTest files Directory"
        required: false
        type: string
        default: "tests/requirements/dependencies"

      package_location:
        description: "Packages/Modules Directory"
        required: false
        type: string
        default: "packages/requirements/dependencies"

      github_action:
        description: "Target GitHub-Actions Path"
        required: false
        type: string
        default: ".github/actions/test-summary"

  push:
    branches:
      - master
      - functional
    paths:
      - .github/workflows/**
      - .github/actions/**

    pull_request:
      branches:
        - master

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "pkgs.module-dependencies",
          "params": {
            "pytests_location": {
              "id": "PyTest Location",
              "event": "${{ github.event.inputs.pytests_location }}",
              "value": "tests/requirements/dependencies"
            },
            "package_location": {
              "id": "Package Location",
              "event": "${{ github.event.inputs.package_location }}",
              "value": "packages/requirements/dependencies"
            },
            "github_action": {
              "id": "GitHub Action",
              "event": "${{ github.event.inputs.github_action }}",
              "value": ".github/actions/test-summary"
            }
          }
        }

  debug-validations:
    needs: workflow-parameters
    runs-on: ubuntu-latest
    steps:
      - name: Debug Validated Params
        run: |

          echo "DEBUGGING VALIDATED PARAMS:"
          echo "Raw: ${{ needs.workflow-parameters.outputs.validated }}"
          echo "Property: ${{ needs.workflow-parameters.outputs.validated.package_location }}"
          echo "To JSON: ${{ toJson( needs.workflow-parameters.outputs.validated ).pytests_location }}"
          echo "From JSON: ${{ fromJson( needs.workflow-parameters.outputs.validated ).pytests_location }}"
          echo "Parsed: $(echo '${{ needs.workflow-parameters.outputs.validated }}' | jq .)"

  install-packages:
    needs: workflow-parameters
    uses: ./.github/workflows/module.install-packages.yaml
    with:
      # package_location: ${{ inputs.package_location }}
      package_location: ${{ needs.workflow-parameters.outputs.validated.package_location }}

  pytest-module:
    needs: install-packages
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      # pytests_location: ${{ inputs.pytests_location }}
      # package_location: ${{ inputs.package_location }}
      pytests_location: ${{ fromJson( needs.workflow-parameters.outputs.validated ).pytests_location }}
      package_location: ${{ fromJson( needs.workflow-parameters.outputs.validated ).package_location }}

  execute-module:
    needs: pytest-module
    if: needs.pytest-module.outputs.aggregated_results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      # package_location: ${{ inputs.package_location }}
      package_location: ${{ fromJson( needs.workflow-parameters.outputs.validated ).package_location }}

  workflow-completed:
    needs: execute-module
    runs-on: ubuntu-latest
    steps:

      - name: Completed Dependencies Module
        id: dependencies_module
        run: |
          echo -e "Completed Dependencies Workflow" ;
