---
## File: .github/workflows/pytest.module-matrix.yaml

name: PyTest - Package Module Matrix
run-name: ${{ github.actor }} -> Package Module Matrix

on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string

      package_location:
        required: true
        type: string

      github_scripts:
        required: false
        type: string
        default: ".github/scripts"

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

    outputs:
      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.workflow-completed.outputs.aggregated_results }}

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "pytest.module-matrix",
          "params": {
            "pytests_location": {
              "id": "PyTest Location",
              "value": "${{ github.event.inputs.pytests_location }}",
              "default": "tests/requirements/dependencies"
            },
            "package_location": {
              "id": "Package Location",
              "value": "${{ github.event.inputs.package_location }}",
              "default": "packages/requirements/dependencies"
            },
            "github_scripts": {
              "id": "GitHub Scripts",
              "value": "${{ github.event.inputs.github_scripts }}",
              "default": ".github/scripts"
            },
            "artifacts_location": {
              "id": "Artifacts Location",
              "value": "${{ github.event.inputs.artifacts_location }}",
              "default": "artifacts"
            }
          }
        }

  parameters:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: PyTest - Module-Matrix (Parameters)
        id: workflow_parameters
        run: |

          echo "PyTests Location: ${{ fromJson(
            needs.workflow.outputs.validated ).pytests_location }}" ;
          echo "Package Location: ${{ fromJson(
            needs.workflow.outputs.validated ).package_location }}" ;
          echo "GitHub Scripts: ${{ fromJson(
            needs.workflow.outputs.validated ).github_scripts }}" ;
          echo "Artifacts Location: ${{ fromJson(
            needs.workflow.outputs.validated ).artifacts_location }}" ;

  extracting-pytests:
    needs: [workflow, parameters]
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      github_scripts: >-
        ${{ fromJson( needs.workflow.outputs.validated ).github_scripts }}
      pytests_location: >-
        ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}

  running-pytests:
    needs: extracting-pytests
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      test_functions: ${{ needs.extracting-pytests.outputs.test_functions }}
      # pytests_location: >-
      #   ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}
      ## Warning: Needs to be fixed
      pytests_location: 'tests/requirements/dependencies'

  aggregating-pytests:
    needs: running-pytests
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      # github_scripts: >-
      #   ${{ fromJson( needs.workflow.outputs.validated ).github_scripts }}
      ## Warning: Needs to be fixed
      github_scripts: ".github/scripts"
      # artifacts_location: >-
      #   ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}
      ## Warning: Needs to be fixed
      artifacts_location: "artifacts"

  workflow-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Workflow Completion
        id: workflow_status
        run: |

          echo "Dependencies Matrix - GitHub Environment:\n${GITHUB_ENV}" ;
