---
## File: pytest.module-matrix.yaml

name: Parallel PyTest - Module (Matrix)
run-name: ${{ github.actor }} -> PyTest Module (Matrix)

on:

  workflow_call:
    inputs:

      pytests_dir:
        required: true
        type: string
        default: false

      packages_dir:
        required: true
        type: string
        default: false

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

  # push:
  #   branches:
  #     - master
  #
  # pull_request:
  #   branches:
  #     - master

env:

  GITHUB_ACTION: "${{ github.workspace }}/.github/actions/test-summary"
  ARTIFACTS_DIR: "${{ github.workspace }}/artifacts"

jobs:

  pytest-params:
    runs-on: ubuntu-latest
    steps:
      - name: Check PyTest Modules
        run: |
          if [[ -z "${{ inputs.pytests_dir }}" ]]; then
            echo -en "Error: inputs.pytests_dir must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid target." ;
            exit 1 ;
          fi ;

  packages-params:
    runs-on: ubuntu-latest
    steps:
      - name: Check Packages Modules
        run: |
          if [[ -z "${{ inputs.packages_dir }}" ]]; then
            echo -en "Error: inputs.packages_dir must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid target." ;
            exit 1 ;
          fi ;

  install-packages:
      uses: ./.github/workflows/module.install-packages.yaml
      with:
        PACKAGES_DIR: ${{ inputs.packages_dir }}

  extract-pytests:
      uses: ./.github/workflows/module.extract-pytests.yaml
      with:
        GITHUB_ACTION: "${{ inputs.github_action }}"

  running-pytests:
      needs: [install-packages, extract-pytests]
      uses: ./.github/workflows/module.running-pytests.yaml
      with:
        test_functions: ${{ needs.extract-pytests.outputs.test_functions }}

  aggregate-test-results:
      needs: running-pytests
      uses: ./.github/workflows/module.aggregate-results.yaml
      with:
        GITHUB_ACTION: "${{ inputs.github_action }}"
