---
## File: pytest.module-matrix.yaml

name: PyTest - Package Module Matrix
run-name: ${{ github.actor }} -> Package Module Matrix

on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string
        default: ''

      package_location:
        required: true
        type: string
        default: ''

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

    outputs:
      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.workflow-completed.outputs.aggregated_results }}

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  workflow-parameters:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "pytest.module-matrix",
          "params": {
            "pytests_location": {
              "PyTest Location": "${{ github.event.inputs.pytests_location }}"
            },
            "package_location": {
              "Package Location": "${{ github.event.inputs.package_location }}"
            },
            "github_action": {
              "GitHub Action": "${{ github.event.inputs.github_action }}"
            },
            "artifacts_location": {
              "Artifacts Location": "${{ github.event.inputs.artifacts_location }}"
            }
          }
        }

  extracting-pytests:
    needs: workflow-parameters
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      github_action: "${{ inputs.github_action }}"

  running-pytests:
    needs: extracting-pytests
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      test_functions: ${{ needs.extracting-pytests.outputs.test_functions }}

  aggregating-pytests:
    needs: running-pytests
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      github_action: "${{ inputs.github_action }}"
      artifacts_location: "${{ inputs.artifacts_location }}"

  workflow-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Listing Entire Project
        id: listing_project
        run: |
          tree -FCla --prune -I .git ${{ github.workspace }} ;

      - name: Workflow Completion
        id: workflow_status
        run: |
          echo "Dependencies Matrix - GitHub Environment:\n${GITHUB_ENV}" ;
