---
## File: pytest.dependencies-module.yaml

name: PyTest - Dependencies Module
run-name: ${{ github.actor }} -> PyTest Dependencies Module

on:

  workflow_dispatch:

    inputs:

      pytests_dir:
        description: 'Directory containing PyTest files'
        required: false
        default: 'tests/requirements/dependencies'

      package_path:
        description: 'Directory containing package files'
        required: false
        default: 'packages/requirements/dependencies'

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  install-packages:
      uses: ./.github/workflows/module.install-packages.yaml
      with:
        package_path: ${{ inputs.package_path }}

  module-matrix:
    uses: ./.github/workflows/pytest.module-matrix.yaml
    with:
      pytests_dir: ${{ inputs.pytests_dir }}
      package_path: ${{ inputs.package_path }}

  execute-module:
    needs: aggregate-test-results
    uses: ./.github/workflows/module.execute-module.yaml
    with:
      package_path: ${{ inputs.package_path }}
