---
## File: .github/workflows/pytest.module-matrix.yaml

name: PyTest - Package Module Matrix
run-name: ${{ github.actor }} -> Package Module Matrix

on:

  workflow_call:

    inputs:

      pytest_files:
        required: false
        type: string
        # default: 'pytest_files.json'

      pytest_mapping:
        required: false
        type: string
        # default: 'pytest_functions.json'

      params:
        required: false
        type: string

    outputs:

      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.pytests-completed.outputs.aggregated_results }}

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: >-
        {
          "workflow": "pytest.module-matrix",
          "inputs": {
            "pytest_files": {
              "id": "PyTest Files",
              "value": "${{ inputs.pytest_files }}",
              "default": "${{ vars.PYTEST_FILES }}"
            },
            "pytest_mapping": {
              "id": "PyTest Mapping",
              "value": "${{ inputs.pytest_mapping }}",
              "default": "${{ vars.PYTEST_MAPPING }}"
            },
            "params": {
              "id": "Workflow Parameters", "value": ${{ inputs.params }}
            }
          }
        }

  parameters:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: PyTest - Module-Matrix (Parameters)
        id: workflow_parameters
        run: |

          echo "PyTest Files: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest_files }}" ;
          echo "PyTest Mapping: ${{ fromJson(
            needs.workflow.outputs.validated ).pytest_mapping }}" ;

          echo "PyTests Location: ${{ fromJson(
            needs.workflow.outputs.validated ).params.pytests_location }}" ;
          echo "Package Location: ${{ fromJson(
            needs.workflow.outputs.validated ).params.package_location }}" ;

          echo "Project Scripts: ${{ fromJson(
            needs.workflow.outputs.validated ).params.project_scripts }}" ;

  extracting-pytests:
    needs: [ workflow, parameters ]
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      pytest: ${{ needs.workflow.outputs.validated }}
      pytest_mapping: ${{ fromJson(
        needs.workflow.outputs.validated ).pytest_mapping }}

  running-pytests:
    needs: [ workflow, parameters, extracting-pytests ]
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      pytest_files: ${{ needs.extracting-pytests.outputs.pytest_files }}
      pytest_functions: ${{ needs.extracting-pytests.outputs.pytest_functions }}
      pytest: ${{ needs.workflow.outputs.validated }}

  aggregating-pytests:
    needs: [ workflow, parameters, running-pytests ]
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      pytest: ${{ needs.workflow.outputs.validated }}

  pytests-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Completed - PyTests Workflow
        id: pytests_workflow
        run: |

          echo -e "Completed - PyTests Workflow" ;
