---
## File: pytest.dependencies-matrix.yaml

name: Requirements - Dependencies Matrix
run-name: ${{ github.actor }} -> Dependencies Matrix

on:

  workflow_call:

    inputs:

      pytests_dir:
        required: true
        type: string
        default: false

      package_path:
        required: true
        type: string
        default: false

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

      artifacts_path:
        required: false
        type: string
        default: "artifacts"

    outputs:
      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.workflow-completed.outputs.aggregated_results }}

# push:
#   branches:
#     - master
#
# pull_request:
#   branches:
#     - master

jobs:

  pytests-location:
    runs-on: ubuntu-latest
    steps:

      - name: Check PyTest Modules
        id: pytests_location
        run: |
          if [[ -z "${{ inputs.pytests_dir }}" ]]; then
            echo -en "Error: inputs.pytests_dir must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid target." ;
            exit 1 ;
          fi ;

  packages-location:
    runs-on: ubuntu-latest
    steps:

      - name: Check Packages Modules
        id: packages_location
        run: |
          if [[ -z "${{ inputs.package_path }}" ]]; then
            echo -en "Error: inputs.package_path must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid target." ;
            exit 1 ;
          fi ;

  extracting-pytests:
    needs: [pytests-location, packages-location]
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      github_action: "${{ inputs.github_action }}"

  running-pytests:
    needs: extracting-pytests
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      test_functions: ${{ needs.extracting-pytests.outputs.test_functions }}

  aggregating-pytests:
    needs: running-pytests
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      github_action: "${{ inputs.github_action }}"
      artifacts_path: "${{ inputs.artifacts_path }}"

  workflow-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Workflow Completion
        id: workflow_status
        run: |
          echo "Dependencies Matrix - GitHub Environment:\n${GITHUB_ENV}" ;
