---
## File: .github/workflows/pytest.module-matrix.yaml

name: PyTest - Package Module Matrix
run-name: ${{ github.actor }} -> Package Module Matrix

on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string

      package_location:
        required: true
        type: string

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

    outputs:
      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.workflow-completed.outputs.aggregated_results }}

  # push:
  #   branches:
  #     - master
  #     - functional
  #   paths:
  #     - .github/workflows/**
  #     - .github/actions/**
  #
  #   pull_request:
  #     branches:
  #       - master

jobs:

  workflow:
    uses: ./.github/workflows/module.validate-parameters.yaml
    with:
      workflow_inputs: |
        {
          "workflow": "pytest.module-matrix",
          "params": {
            "pytests_location": {
              "id": "PyTest Location",
              "event": "${{ github.event.inputs.pytests_location }}",
              "value": "tests/requirements/dependencies"
            },
            "package_location": {
              "id": "Package Location",
              "event": "${{ github.event.inputs.package_location }}",
              "value": "packages/requirements/dependencies"
            },
            "github_action": {
              "id": "GitHub Action",
              "event": "${{ github.event.inputs.github_action }}",
              "value": ".github/actions/test-summary"
            },
            "artifacts_location": {
              "id": "Artifacts Location",
              "value": "${{ inputs.artifacts_location }}"
            }
          }
        }

  testing:
    needs: workflow
    runs-on: ubuntu-latest
    steps:

      - name: PyTest - Module-Matrix (Parameters)
        id: workflow_parameters
        run: |

          echo "PyTests Location: ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}"
          echo "Package Location: ${{ fromJson( needs.workflow.outputs.validated ).package_location }}"
          echo "GitHub Action: ${{ fromJson( needs.workflow.outputs.validated ).github_action }}"
          echo "Artifacts Location: ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}"

  extracting-pytests:
    needs: [workflow, testing]
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      github_action: >
        ${{ fromJson( needs.workflow.outputs.validated ).github_action }}
      pytests_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}

  running-pytests:
    needs: extracting-pytests
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      test_functions: ${{ needs.extracting-pytests.outputs.test_functions }}
      pytests_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}

  aggregating-pytests:
    needs: running-pytests
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      github_action: >
        ${{ fromJson( needs.workflow.outputs.validated ).github_action }}
      artifacts_location: >
        ${{ fromJson( needs.workflow.outputs.validated ).artifacts_location }}

  workflow-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Workflow Completion
        id: workflow_status
        run: |
          echo "Dependencies Matrix - GitHub Environment:\n${GITHUB_ENV}" ;
