name: Parallel PyTest - Dependencies (Jobs)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pytest
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install pytest

  test_load_requirements_valid:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_load_requirements_valid
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_load_requirements_valid

  test_load_requirements_missing:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_load_requirements_missing
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_load_requirements_missing

  test_load_requirements_invalid_json:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_load_requirements_invalid_json
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_load_requirements_invalid_json

  test_is_package_installed:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_is_package_installed
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_is_package_installed

  test_install_requirements:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_install_requirements
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_install_requirements

  test_parse_arguments_default:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_parse_arguments_default
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_parse_arguments_default

  test_parse_arguments_custom:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_parse_arguments_custom
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_parse_arguments_custom

  test_update_installed_packages:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_update_installed_packages
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_update_installed_packages

  test_print_installed_packages:
    needs: install-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test_print_installed_packages
        run: pytest tests/requirements/dependencies/test_dependencies.py::test_print_installed_packages
