---
name: Parallel PyTest - Dependencies (Matrix)
run-name: ${{ github.actor }} -> Dependencies (Matrix)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_DIR: tests/requirements/dependencies/

jobs:

  install-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate requirements.txt from JSON
        run: |
          jq -r '
            .dependencies[] |
            if .version.target then
              "\(.package)==\(.version.target)"
            else
              .package
            end' packages/requirements/requirements.json > requirements.txt
          echo "Generated requirements.txt:"
          cat requirements.txt

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Generate Final requirements.txt
        run: |
          pip freeze > final-requirements.txt
          echo "Generated final-requirements.txt:"
          cat final-requirements.txt

      - name: Upload requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: |
            requirements.txt
            final-requirements.txt

  extract-tests:
    runs-on: ubuntu-latest
    outputs:
      test_functions: ${{ steps.extract.outputs.tests }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Test Functions
        id: extract
        run: |
          TESTS=$(python -c "import re, json, sys; \
            f = open('${{ env.TEST_DIR }}test_dependencies.py', 'r'); \
            tests = re.findall(r'^def (test_[a-zA-Z0-9_]+)', f.read(), re.MULTILINE); \
            f.close(); \
            sys.stdout.write(json.dumps(tests if tests else ['dummy_test_function']))")

          echo "Extracted test functions: $TESTS"

          # Ensure valid JSON before passing to GitHub Actions output
          echo "tests=$TESTS" >> "$GITHUB_OUTPUT"

  run-tests:
    needs: [install-pytest, extract-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        test_function: ${{ fromJson(needs.extract-tests.outputs.test_functions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ matrix.python-version }}-${{ matrix.test_function }}-

      - name: Download requirements.txt
        uses: actions/download-artifact@v4
        with:
          name: requirements-${{ matrix.python-version }}
          path: .

      - name: Verify Downloaded Artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -l

      - name: Verify requirements.txt Exists
        run: |
          echo "Checking if requirements.txt exists..."
          if [[ -f requirements.txt ]]; then
            echo "requirements.txt found!"
            echo "Contents of requirements.txt:"
            cat requirements.txt
          else
            echo "ERROR: requirements.txt is missing!"
            exit 1
          fi

      - name: Reinstall Dependencies from Cache
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Pytest Function
        run: |
          pytest -v --junitxml=test-results.xml \
          ${{ env.TEST_DIR }}test_dependencies.py::${{ matrix.test_function }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}-${{ matrix.test_function }}
          path: test-results.xml

  aggregate-test-results:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate JSON Summary
        run: |
          echo "Aggregating test results..."
          find artifacts/ -type f -name "*.xml" > test_files.txt ;

          # Generate JSON using jq for proper formatting
          jq -n '{test_summary: []}' > test_results.json 2>/dev/null ;

          while read -r FILE; do

            # Extract test function name
            full_testname=$( basename $( dirname "${FILE}" ) ) ;
            # Extract Python version
            python_version="$(
              echo "${full_testname}" | grep -oP '(?<=pytest-results-)[0-9]+\.[0-9]+'
            )" ;
            # Remove prefix
            test_name="$(
              echo "${full_testname}" | sed -E "s/pytest-results-[0-9]+\.[0-9]+-//"
            )" ;

            total_tests=$(
              grep -oP '(?<=tests=")[0-9]+' "$FILE" | paste -sd+ | bc
            ) ;
            failed_tests=$(
              grep -oP '(?<=failures=")[0-9]+' "$FILE" | paste -sd+ | bc
            ) ;
            SKIPPED_TESTS=$(
              grep -oP '(?<=skipped=")[0-9]+' "$FILE" | paste -sd+ | bc
            ) ;
            passed_tests=$((
              total_tests - failed_tests - skipped_tests
            )) ;

            declare -a report=();
             report_structure=('[ { "python_version": "'${python_version}'",');
            report_structure+=('"test_name": "'${test_name}'",');
            report_structure+=('"total": '${total}',');
            report_structure+=('"passed": '${passed}',');
            report_structure+=('"failed": '${failed}',');
            report_structure+=('"skipped": '${skipped}' } ]');

            jq --arg python_version "${python_version}" \
               --arg test_name "${test_name}" \
               --argjson total "${total_tests}" \
               --argjson passed "${passed_tests}" \
               --argjson failed "${failed_tests}" \
               --argjson skipped "${skipped_tests}" \
               '.test_summary += '${report_structure} \
               test_results.json > temp.json && mv temp.json test_results.json ;

          done < test_files.txt ;

          # ✅ Print JSON as a single formatted block
          cat test_results.json | jq .

      - name: Upload JSON Summary
        uses: actions/upload-artifact@v4
        with:
          name: test-results-summary
          path: test_results.json
