---
## File: .github/workflows/pytest.module-matrix.yaml
## Version: 0.2.2

name: PyTest - Package Module Matrix
run-name: ${{ github.actor }} -> Package Module Matrix

on:

  workflow_call:

    inputs:

      pytests_location:
        required: true
        type: string

      packages_location:
        required: true
        type: string

      github_action:
        required: false
        type: string
        default: ".github/actions/test-summary"

      artifacts_location:
        required: false
        type: string
        default: "artifacts"

    outputs:
      aggregated_results:
        description: "Providing PyTest Results Aggregation status"
        value: ${{ jobs.workflow-completed.outputs.aggregated_results }}

jobs:

  pytests-location:
    runs-on: ubuntu-latest
    steps:

      - name: Check PyTests Location
        id: pytests_location
        run: |
          if [[ -z "${{ inputs.pytests_location }}" ]]; then
            echo -en "Error: inputs.pytests_location must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid PyTests Location." ;
            exit 1 ;
          fi ;

  packages-location:
    runs-on: ubuntu-latest
    steps:

      - name: Check Packages Location
        id: packages_location
        run: |
          if [[ -z "${{ inputs.packages_location }}" ]]; then
            echo -en "Error: inputs.packages_location must be provided. " ;
            echo -e  "The workflow cannot proceed without a valid target." ;
            exit 1 ;
          fi ;

  extracting-pytests:
    needs: [pytests-location, packages-location]
    uses: ./.github/workflows/module.extract-pytests.yaml
    with:
      github_action: "${{ inputs.github_action }}"
      pytests_location: "${{ inputs.pytests_location }}"

  running-pytests:
    needs: extracting-pytests
    uses: ./.github/workflows/module.running-pytests.yaml
    with:
      test_functions: ${{ needs.extracting-pytests.outputs.test_functions }}

  aggregating-pytests:
    needs: running-pytests
    uses: ./.github/workflows/module.aggregate-results.yaml
    with:
      github_action: "${{ inputs.github_action }}"
      artifacts_location: "${{ inputs.artifacts_location }}"

  workflow-completed:
    needs: aggregating-pytests
    runs-on: ubuntu-latest
    outputs:
      aggregated_results: ${{ needs.aggregating-pytests.outputs.aggregated_results }}
    steps:

      - name: Listing Entire Project
        id: listing_project
        run: |
          tree -FCla --prune -I .git ${{ github.workspace }} ;

      - name: Debug - Extracted Test Functions
        run: |
          echo "Extracted Test Functions JSON: ${{ needs.extracting-pytests.outputs.test_functions }}"

      - name: Workflow Completion
        id: workflow_status
        run: |
          echo "Dependencies Matrix - GitHub Environment:\n${GITHUB_ENV}" ;
